In [88]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
books = pd.read_csv('BX-Books.csv', sep=';', error_bad_lines=False, encoding="latin-1")
books.columns = ['ISBN', 'bookTitle', 'bookAuthor', 'yearOfPublication', 'publisher', 'imageUrlS', 'imageUrlM', 'imageUrlL']
users = pd.read_csv('BX-Users.csv', sep=';', error_bad_lines=False, encoding="latin-1")
users.columns = ['userID', 'Location', 'Age']
ratings = pd.read_csv('BX-Book-Ratings.csv', sep=';', error_bad_lines=False, encoding="latin-1")
ratings.columns = ['userID', 'ISBN', 'bookRating']

b'Skipping line 6452: expected 8 fields, saw 9\nSkipping line 43667: expected 8 fields, saw 10\nSkipping line 51751: expected 8 fields, saw 9\n'
b'Skipping line 92038: expected 8 fields, saw 9\nSkipping line 104319: expected 8 fields, saw 9\nSkipping line 121768: expected 8 fields, saw 9\n'
b'Skipping line 144058: expected 8 fields, saw 9\nSkipping line 150789: expected 8 fields, saw 9\nSkipping line 157128: expected 8 fields, saw 9\nSkipping line 180189: expected 8 fields, saw 9\nSkipping line 185738: expected 8 fields, saw 9\n'
b'Skipping line 209388: expected 8 fields, saw 9\nSkipping line 220626: expected 8 fields, saw 9\nSkipping line 227933: expected 8 fields, saw 11\nSkipping line 228957: expected 8 fields, saw 10\nSkipping line 245933: expected 8 fields, saw 9\nSkipping line 251296: expected 8 fields, saw 9\nSkipping line 259941: expected 8 fields, saw 9\nSkipping line 261529: expected 8 fields, saw 9\n'
/home/harsh/anaconda3/lib/python3.7/site-packages/IPython/core/interactive

In [89]:
ratings.head()

userID        ISBN  bookRating
0  276725  034545104X           0
1  276726  0155061224           5
2  276727  0446520802           0
3  276729  052165615X           3
4  276729  0521795028           6

In [90]:
ratingsMerge = ratings.merge(books, on='ISBN')

In [91]:
ratingsMerge.head()

userID        ISBN  bookRating             bookTitle  bookAuthor  \
0  276725  034545104X           0  Flesh Tones: A Novel  M. J. Rose   
1    2313  034545104X           5  Flesh Tones: A Novel  M. J. Rose   
2    6543  034545104X           0  Flesh Tones: A Novel  M. J. Rose   
3    8680  034545104X           5  Flesh Tones: A Novel  M. J. Rose   
4   10314  034545104X           9  Flesh Tones: A Novel  M. J. Rose   

  yearOfPublication         publisher  \
0              2002  Ballantine Books   
1              2002  Ballantine Books   
2              2002  Ballantine Books   
3              2002  Ballantine Books   
4              2002  Ballantine Books   

                                           imageUrlS  \
0  http://images.amazon.com/images/P/034545104X.0...   
1  http://images.amazon.com/images/P/034545104X.0...   
2  http://images.amazon.com/images/P/034545104X.0...   
3  http://images.amazon.com/images/P/034545104X.0...   
4  http://images.amazon.com/images/P/034545104X.0...   

                                           imageUrlM  \
0  http://images.amazon.com/images/P/034545104X.0...   
1  http://images.amazon.com/images/P/034545104X.0...   
2  http://images.amazon.com/images/P/034545104X.0...   
3  http://images.amazon.com/images/P/034545104X.0...   
4  http://images.amazon.com/images/P/034545104X.0...   

                                           imageUrlL  
0  http://images.amazon.com/images/P/034545104X.0...  
1  http://images.amazon.com/images/P/034545104X.0...  
2  http://images.amazon.com/images/P/034545104X.0...  
3  http://images.amazon.com/images/P/034545104X.0...  
4  http://images.amazon.com/images/P/034545104X.0...

In [92]:
columnsToDrop = ['yearOfPublication', 'publisher', 'bookAuthor', 'imageUrlS', 'imageUrlM', 'imageUrlL', 'userID']

In [93]:
ratingsMerge = ratingsMerge.drop(columnsToDrop, axis =1)

In [94]:
ratingsMerge.head()

ISBN  bookRating             bookTitle
0  034545104X           0  Flesh Tones: A Novel
1  034545104X           5  Flesh Tones: A Novel
2  034545104X           0  Flesh Tones: A Novel
3  034545104X           5  Flesh Tones: A Novel
4  034545104X           9  Flesh Tones: A Novel

In [95]:
finalRatingCleaned = ratingsMerge.groupby('ISBN')['bookRating'].count().reset_index().rename(columns ={'bookRating':'ratingCount'})
totalRatingCount.head()

ISBN  ratingCount
0  0000913154            1
1  0001010565            2
2  0001046438            1
3  0001046713            1
4  000104687X            1

In [96]:
finalRatingCleaned['averageRating'] = ratingsMerge.groupby('ISBN')['bookRating'].mean().reset_index()['bookRating']
finalRatingCleaned.head()

ISBN  ratingCount  averageRating
0  0000913154            1            8.0
1  0001010565            2            0.0
2  0001046438            1            9.0
3  0001046713            1            0.0
4  000104687X            1            6.0

 lets check if any duplicate book is present in finalRatingCleaned table

In [97]:
anyDuplicateRecord = finalRatingCleaned['ISBN'].value_counts()
anyDuplicateRecord.head()

039448438X    1
155773416X    1
0399142622    1
0373691874    1
0061008524    1
Name: ISBN, dtype: int64

In [98]:
anyDuplicateRecord[anyDuplicateRecord>1].index

Index([], dtype='object')

here index will return first column values(i.e. ISBN) from anyDuplicateRecord table

In [99]:
ratings.head()

userID        ISBN  bookRating
0  276725  034545104X           0
1  276726  0155061224           5
2  276727  0446520802           0
3  276729  052165615X           3
4  276729  0521795028           6

In [100]:
users.head()

userID                            Location   Age
0       1                  nyc, new york, usa   NaN
1       2           stockton, california, usa  18.0
2       3     moscow, yukon territory, russia   NaN
3       4           porto, v.n.gaia, portugal  17.0
4       5  farnborough, hants, united kingdom   NaN

# filter only users from US and Canada

In [101]:
userInUsCanada = pd.Series(users[users['Location'].str.contains('usa|canada')]['userID'],dtype='int32')
userInUsCanada

0              1
1              2
5              6
6              7
7              8
           ...  
278848    278849
278850    278851
278853    278854
278855    278856
278856    278857
Name: userID, Length: 161633, dtype: int32

In [102]:
ratingsofUSCanada = ratings[ratings['userID'].isin(userInUsCanada)]

In [103]:
ratingsofUSCanada

userID         ISBN  bookRating
0        276725   034545104X           0
1        276726   0155061224           5
8        276744   038550120X           7
16       276747   0060517794           9
17       276747   0451192001           0
...         ...          ...         ...
1149775  276704   1563526298           9
1149776  276706   0679447156           0
1149777  276709   0515107662          10
1149778  276721   0590442449          10
1149779  276723  05162443314           8

[872045 rows x 3 columns]

In [104]:
users.query('userID == 276744')

userID                   Location  Age
276743  276744  torrance, california, usa  NaN

# From ratingsofUSCanada table  users with less than 200 ratings, and books with less than 100 ratings are excluded.

In [105]:
countUsers = ratingsofUSCanada['userID'].value_counts()
countBooks = ratingsofUSCanada['ISBN'].value_counts()

In [106]:
ratingsofUSCanada = ratingsofUSCanada[ratingsofUSCanada['userID'].isin(countUsers[countUsers>=200].index)]
ratingsofUSCanada = ratingsofUSCanada[ratingsofUSCanada['ISBN'].isin(countBooks[countBooks>=100].index)]

In [107]:
ratingsofUSCanada.head()

userID        ISBN  bookRating
1456  277427  002542730X          10
1469  277427  0060930535           0
1471  277427  0060934417           0
1474  277427  0061009059           9
1484  277427  0140067477           0

In [108]:
ratingsofUSCanada = ratingsofUSCanada.merge(books, left_on='ISBN', right_on='ISBN', how='left')

In [109]:
ratingsofUSCanada = ratingsofUSCanada.drop(['yearOfPublication', 'publisher', 'bookAuthor', 'imageUrlS', 'imageUrlM', 'imageUrlL'], axis = 1)
ratingsofUSCanada.head()

userID        ISBN  bookRating  \
0  277427  002542730X          10   
1  277427  0060930535           0   
2  277427  0060934417           0   
3  277427  0061009059           9   
4  277427  0140067477           0   

                                           bookTitle  
0  Politically Correct Bedtime Stories: Modern Ta...  
1                      The Poisonwood Bible: A Novel  
2                                 Bel Canto: A Novel  
3  One for the Money (Stephanie Plum Novels (Pape...  
4                                    The Tao of Pooh

In [110]:
ratingsofUSCanada = ratingsofUSCanada.drop_duplicates(['userID', 'bookTitle'])

In [115]:
pivotTable = ratingsofUSCanada.pivot(index = 'bookTitle', columns='userID', values='bookRating').fillna(0)
pivotTable.head()

userID               254     2276    2766    2977    3363    4017    4385    \
bookTitle                                                                     
NaN                     8.0     0.0     0.0     0.0     0.0     9.0     0.0   
1984                    9.0     0.0     0.0     0.0     0.0     0.0     0.0   
1st to Die: A Novel     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2nd Chance              0.0    10.0     0.0     0.0     0.0     0.0     0.0   
4 Blondes               0.0     0.0     0.0     0.0     0.0     0.0     0.0   

userID               6242    6251    6323    ...  271448  271705  273979  \
bookTitle                                    ...                           
NaN                     0.0     0.0     0.0  ...     0.0     0.0     0.0   
1984                    0.0     0.0     0.0  ...     0.0    10.0     0.0   
1st to Die: A Novel     0.0     0.0     0.0  ...     0.0     0.0     0.0   
2nd Chance              0.0     0.0     0.0  ...     0.0     0.0     0.0   
4 Blondes               0.0     0.0     0.0  ...     0.0     0.0     0.0   

userID               274061  274308  274808  275970  277427  277639  278418  
bookTitle                                                                    
NaN                     0.0     0.0     0.0     0.0     0.0     0.0     0.0  
1984                    0.0     0.0     0.0     0.0     0.0     0.0     0.0  
1st to Die: A Novel     0.0     0.0     0.0     0.0     0.0     0.0     0.0  
2nd Chance              0.0     0.0     0.0     0.0     0.0     0.0     0.0  
4 Blondes               0.0     0.0     0.0     0.0     0.0     0.0     0.0  

[5 rows x 733 columns]

In [119]:
from scipy.sparse import csr_matrix
matrix = csr_matrix(pivotTable.values)

In [120]:
from sklearn.neighbors import NearestNeighbors
modelKNN = NearestNeighbors(metric='cosine', algorithm='brute')

In [121]:
queryIndex = np.random.choice(pivotTable.shape[0])
queryIndex

381

In [124]:
modelKNN.fit(matrix)

NearestNeighbors(algorithm='brute', leaf_size=30, metric='cosine',
                 metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                 radius=1.0)

In [125]:
distance, indices = modelKNN.kneighbors(pivotTable.iloc[queryIndex,:].values.reshape(1, -1), n_neighbors = 6)

In [126]:
pivotTable.index[queryIndex]

"The Book of Ruth (Oprah's Book Club (Paperback))"

In [127]:
distance

array([[0.        , 0.71976899, 0.76954616, 0.7744676 , 0.78090808,
        0.79734923]])

In [128]:
indices

array([[381, 317, 192, 536, 454, 421]])

In [130]:
print(indices.flatten())

[381 317 192 536 454 421]


# Here above flatten it into one dimension array so that we can fetch values by array indexing

In [133]:
for i in range(0, len(distance.flatten())):
    if(i==0):
        print('we are searching for movie:{}'.format(pivotTable.index[indices.flatten()[i]]))
    else:
        print('similar movie is{} and distance is {}'.format(pivotTable.index[indices.flatten()[i]],distance.flatten()[i]))
    

we are searching for movie:The Book of Ruth (Oprah's Book Club (Paperback))
similar movie isSTONES FROM THE RIVER and distance is 0.7197689873977017
similar movie isHere on Earth and distance is 0.769546161332597
similar movie isVinegar Hill (Oprah's Book Club (Paperback)) and distance is 0.7744675972290382
similar movie isThe Lovely Bones: A Novel and distance is 0.7809080828085111
similar movie isThe Girls' Guide to Hunting and Fishing and distance is 0.7973492348185378
